### PR TITLE
SC-7096 Up-version emoji

### PR DESCRIPTION
**Pull request by Younghyo**
We need the newer version of `kss` to split the problematic sentence we have met since the version of it works well on it. (I've attached the sentence at the end of this text.)

This `kss` library is forked to up-version the emoji library it requires. Since our pylibs is already using `emoji==2.5.1`, this is a conflict between the `3.7.3` version of `kss`. Luckily, `kss` has only small code for this so they are modified to be able to go with `emoji=2.5.1`. It seems they just collect the emoji lookup tables and the newer version of emoji doesn't have the exactly same attributes that `kss` has depended on so they were fixed with similar function but the result would be same. The reason why we don't use the latest version of `kss` which is `4.x.x` is that it again cannot split the problematic sentence we had. I think utilizing `mecab` in their new version messed up something again.

The problematics sentence is like below.
```
"이 한국의 전통적인 사무공간'이라고 하면 어떤 이미지가 있잖아요. 책상 들이 있고, 파티션이 있고, 다 다닥다닥 붙어 있고 이런 사무실은 좀 언제부터 생겨난 거라고 볼 수 있을까요? 국내에서는 경제성장이 굉장히 60년대부터 시작해서 7, 80년대 엄청 활발해졌다 나요. 저희가 지금 상상하는 오피스는 80년대 이후에 등장했다고 보시면 되고요. 3층 그룹영어, 토익만 그런 사무실에서 지금처럼 어떤 레이아웃의 개념을 가진 오피스는 90년대 이후에나 보편화됐다고 보시면 됩니다. 미국에서는 사실 그런 오피스에 대한 논의가 훨씬 저희 보다 앞섰고, 미국에서는 최초로 큐빅 글이나 어떤 시스템 가구 라고 할만한 가구가 이미 1960년대에 등장을 했어요. 1964년에 이제 허먼 밀러사의 액션 오피스라는 제품이 등장을 한 것을 시초로 보는데. 그 액션 오피스들, 그건 어떤. 거예요? 미국에서 사무실 근로자가 막 생기기 시작할 때여서 사무실에서 하는 노동도 마치 공장에서 하는 노동과 동일하다고 본 거에요. 공장의 체계화된 작업을 관리 감독하는 것처럼, 사무실에서도 그걸 관리 감독하는 방식으로 해서 노동자들이 쉬지 않고 일을 할 수 있게 업무 효율에 엄청 방점을 둔 거죠. 인간보다는 시스템에 되게 집중을 해서 테일러리즘이라는 개념이 굉장히 보편화됐어요. 테일러리즘에 사무실을 만들다 보니 비인간적인 그런 모습들이 반발 작용하면서 액션 오피스를 디자인한 로버트 프로스트 라는 디자이너가 사무실의 노동은 공장 노동과는 다르다. 지식노동이다. 그래서 지식은 사람들이 몸을 잘 쓸 수 있게 그것을 지원해줘야지 된다 해가지고 원래 자유롭게 그 영역 안에서 업무를 볼 수 있게 시작했던 디자인인데, 사실 기업을 운영하는 경영자 입장이나 임원들 입장에서는 여전히 관리 좀 효율, 이 공간을 어떻게 하면 빨리 빨리 복제해서 쓸 수 있고, 사람들이 들고 날 때 빨리 카피해가지고 배치를 쉽게 하고 이런 것들에 더 방점을 찍으면서 시장도 사실 그 니즈에 맞게 바뀌게 된 거죠. 큐비클이 똑같은 모듈로 되어 있고 그걸 그대로 복제해서 배치하기가 좋잖아요. 그런 관점에서 한 동안 큐비클이 굉장히 오피스를 장악을 했었죠. 그치만 단점 같은 게 있었다면 다 같이 창조적으로 머리 쓰는 일을 하고 소통해야 되는 시대에는 이렇게 부적합했다. 그래서 이제 사라졌다 이렇게 볼 수 있겠네요. 2000년대 들어서 내에 진짜 인터넷이 되거나 인터넷, 이메일 이런 것들이 활발해지고 소통교류협력 이런 것들이 키워드로 부상하면서 오피스가 좀 열리게 되고 미국에서는 사실 되게 빅 테이블이 있죠. 우리 스타벅스에서 큰 테이블에서 일하는 것처럼 벤칭 이라고 하는 그 제품들이 그때 당시에 굉장히 많이 나왔어요. 개인 어떤 업무효율도 중요하지만 이 지식산업사회에서 서로 소통하고 협업하고 아이디어 내고 이런 게 굉장히 중요해지면서 흐름이 바뀐 거죠. 근데 생각해보면 오피스가 정말 많이 바뀐 것 같아요. 제가 공구학번이거든요. 근데 그때 교수님중에 한 분이 미국 실리콘밸리 에는 사무실을 미끄럼틀이 있는 데가 있다. 같이 수업 듣던 애들도 그게 되게 충격이었거든요. 근데 지금 가서 보면은 미끄럼틀 봐도 별 감흥이 없기는 하지만. 근데 이게 정말 한 10년 사이에 굉장히 많은 것들이 바뀐 거 같아요. 지금의 트렌드는 좀 어떻다라고 볼 수 있을까요? 말씀하신 것처럼 진짜 경제 성장도 엄청 압축해서 짧은 시간에 했고 이런 변화가 진짜 짧은 시간에 일어난 것 같아요. 국내에서는 선진상완 경우 구글이나 페이스북 같은 공간을 찾아볼 수 없었는데, 네이버가 분당의 그린팩토리라는 건물을 새로 만들면서 어 뭔가 좀 해외에 같은 오피스 인데 이러면서 그 때부터 이제 조금 그 사무환경의 달라진 모습을 사람들이 보기 시작했고 지금은 구글 미끄럼틀 보셔도 감흥이 없다고 하신 것처럼 사람들이 3D 환경에 대한 눈높이가 엄청 올라갔죠. 저희가 재미 삼아서 사무 공간의 변화들을 대한민국 지난 한 10년, 15년 정도 봤을 때 한번 같이 좀 계보를 써 봐도 괜찮을 것 같아요. 이런 회사들이 많은 변화를 이끌었다. 네이버가 처음에 나왔을 때 진짜 핫이슈였고, 그 전에 오피스는 업무공간 이외의 어떤 공간, 프로그램, 우리가 지금 뭔가 복지처럼 느껴지는 편의시설, 도서관 헬스 케어하는 공간 뭐 이런 것들을 기업들이 우선순위에 두지 않았어요. 네이버가 그렇게 완전 새로운 프로그램들을 굉장히 적극적으로 도입했고 특히나 저층부 네이버라이브러리를 오픈을 하면서 그걸 커뮤니티에 공개했어요. 직원들만 들어갈 수 있는 건물이 아니라 일반인들도 동네 주민들도 그. 침대 공용 공간에 들어와서 이용할 수 있게끔 열린 공간으로 만들고, 그래서 여러가지로 굉장히 이슈가 됐던 오피스 빌딩이죠. 네이버가 그린팩토리에 하기 전만 해도 사실 밤새도록 일하고 책상 밑에서 자고 이런 이미지가 있었어요. 성남 판교에 모여서 정말 등대 처럼 불을 밝히는 그런 문화가 있었는데, 네이버가 아이티 회사에서 일하는 사람들에 대한 이미지를 되게 많이 바꿨던 그런 사건인 것 같기는 해요. 맞아요. 그리고 컬러도 굉장히 알록달록하게 있었어요. 그 전에 오피스는 뭔가 칙칙 칙칙하고 모노톤이고 이런 느낌이었는데, 네이버는 일본과 굉장히 캐주얼하고 진짜 구글의 오피스를 연상시키는 우리나라에도 이런 오피스가 드디어 생겼구나 이런 느낌을 줬었죠. 거기에 이어서 2010년대 배달의 민족 방위동 빌딩이 또 되게 신선한 충격을 줬던 것 같아요. 그래도 그린팩토리하면 뭔가 좀 직장인들이 일하는 공간 이런 느낌은 또 있었는데, 배달의민족 같은 경우에 계단이 됐건 아니면 문짝이 됐건 군데군데 배달의민족 특유의 아이덴티티로 농담같은 거 적어놓고 그리고 김봉진 창업자께서 물이 있는 곳에 사람들이 모인다 라고 하면서 물을 떠먹거나 커피 사먹거나 이런 것들을 각 층마다 중앙에 배치를 하면서 소통같은걸 이끌어내고 중간중간에 웃고 대화할 수 있는 포인트들을 되게 많이 숨겨놔서 미션과 기업 문화를 되게 개성있게 녹여낸 건물로써 굉장히 많은 스타트업한테 영향을 주고 또 많이 따라하게 되고 그런 부분들이 있었던 것 같아요. 요즘 오피스 내에 단순히 그냥 업무를 해야 되서 의무적으로 와야 되는 공간을 더 넘어서 직원들이 오고 싶은 공간, 직원들을 끌어당기는 공간, 회사 차원에서는 이 기업의 조직 문화나 업무 방식을 전파하고 브랜딩하는 그런 공간으로 진화하고 있는 것 같아요. 일하기 좋은 오피스의 조건, 이런 것들은 어떻게 정리해 볼 수 있을까요? 1위 크게 두 가지를 얘기해요. 개인, 업무, 그리고 함께하는 협업. 그래서 이 개인 업무랑 협업이 둘 다 잘되야지 일하기 좋은 곳이죠. 2010년대 만해도 정말 소통과 협업이 훨씬 되게 중요했어요. 그래서 스티브잡스가 그 픽사 사옥 지을 때 한 개 층에 화장실을 한 개만 둬서 우연한 만남, 세렌디피티를 일어나게 설계를 하겠다라고 얘기했던 것도 같은 맥락이라고 볼 수가 있죠. 팬덤이익을 거치면서 굉장히 여러 논의가 있었는데요. 요즘에는 다시모리 개인 업무집중 이게 굉장히 중요한 키워드로 다시 떠오르고 있어요. 집에서 내가 나 혼자 몰입해서 일을 해 봤잖아요. 회의를 잡고 들어가야 된다고. 날은 업무 방해 없이 어쨌든 내가 내 일하는 환경을 컨트롤하는 경험을 했기 때문에 오피스에 와서도 똑같이 그런 걸 원하게 된 거예요. 직원들이 구글 베이비캔버스도 1층은 전체 공용 공간이고 업무공간은 2층으로 아예 분리한 것처럼 분리되는 방향으로 가고 있는 것 같아요. 미국은 사실 더 심하잖아요. 그 재택 근무를 되게 직원들이 강하게 주장하고 리턴 투 오피스를 하려는 회사의 정책에 굉장히 반발해서 회사도 불사하겠다. 대퇴사'의 시대에 막 이러면서 기업이랑 직원이랑 굉장히 이런 갈등이 있었는데."
```

### CODE REVIEW

**Review by dasony — APPROVED** [review]
I don't love having another forked repository, but LGTM.

**Review by therese-lee — APPROVED** [review]
LGTM. Did we decide using this forked version?

**Review by jinhyung — COMMENTED** [review]
As long as @dasony is okay with this forked repo, I'm fine, too.

Maybe we should send the patch to the original repo?

**Comment by Younghyo** [comment]
We decided to cancel to fork this repository but remove apostrophes in ASRWords. See [this PR](https://github.com/xl8-ai/AutoTemplate/pull/128).

**Pull request closed without merging**
